'use client';
import { useEffect, useState } from 'react';
import { CheckCircle2, Clock3, LogOut, PackageCheck, RefreshCw, ShieldCheck } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { type InspectionRecord, levelLabels } from '@/lib/inspection-types';

export function UserPortal() {
  const [records, setRecords] = useState<InspectionRecord[]>([]);
  const [loading, setLoading] = useState(true);
  async function loadRecords() { setLoading(true); try { const response = await fetch('/api/inspections?scope=user', { cache: 'no-store' }); if (response.ok) setRecords(((await response.json()) as { records: InspectionRecord[] }).records); } finally { setLoading(false); } }
  useEffect(() => { const first = window.setTimeout(() => void loadRecords(), 0); const timer = window.setInterval(() => void loadRecords(), 8000); return () => { window.clearTimeout(first); window.clearInterval(timer); }; }, []);
  return <div className="min-h-screen bg-[var(--workspace)] text-slate-900"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-[76px] max-w-6xl items-center px-5"><div className="grid size-10 place-items-center rounded-xl bg-[#e1251b] text-white"><PackageCheck className="size-5" /></div><div className="ml-3"><p className="font-semibold">包裹智检 · 使用者端</p><p className="text-xs text-slate-400">人工复核结果查询</p></div><a href="/" className="ml-auto inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm text-slate-500 hover:bg-slate-50"><LogOut className="size-4" />退出</a></div></header>
    <main className="mx-auto max-w-6xl px-5 py-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><span className="rounded-md bg-blue-50 px-2 py-1 text-xs font-semibold text-blue-700">使用者视图</span><h1 className="mt-4 text-2xl font-bold">人工复核结果</h1><p className="mt-2 text-sm text-slate-500">这里只显示工作人员已经确认并提交的最终定损结果。</p></div><Button variant="outline" onClick={() => void loadRecords()} disabled={loading}><RefreshCw className={`size-4 ${loading ? 'animate-spin' : ''}`} />刷新结果</Button></div>
      <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{!loading && records.length === 0 ? <div className="col-span-full grid min-h-72 place-items-center rounded-2xl border border-slate-200 bg-white text-center"><div><Clock3 className="mx-auto size-8 text-slate-300" /><h2 className="mt-4 font-semibold text-slate-700">暂无已复核结果</h2><p className="mt-2 text-sm text-slate-400">工作人员提交复核后，这里会自动出现结果。</p></div></div> : records.map((record) => <article key={record.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-slate-800">{record.waybill}</p><p className="mt-1 text-xs text-slate-400">{record.taskNo}</p></div><Badge className="bg-emerald-50 text-emerald-700"><CheckCircle2 className="size-3" />已复核</Badge></div><div className="mt-5 rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-400">最终定损等级</p><p className="mt-2 text-lg font-bold text-[#d92319]">{levelLabels[record.reviewLevel ?? record.aiLevel]}</p></div><dl className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-slate-400">破损类型</dt><dd className="mt-1 font-medium text-slate-700">{record.damageTypes.join('、')}</dd></div><div><dt className="text-slate-400">复核人员</dt><dd className="mt-1 font-medium text-slate-700">{record.reviewer || '检测专员'}</dd></div></dl>{record.reviewNote && <div className="mt-4 rounded-xl border border-blue-100 bg-blue-50/60 p-3 text-xs leading-5 text-blue-700"><ShieldCheck className="mb-1 size-4" />{record.reviewNote}</div>}<p className="mt-4 text-xs text-slate-400">复核时间：{new Date(record.updatedAt).toLocaleString('zh-CN')}</p></article>)}</div>
    </main></div>;
}
