import { ArrowRight, ClipboardCheck, LayoutDashboard, PackageCheck, ShieldCheck, UserRound } from 'lucide-react';

export default function Home() {
  return <main className="min-h-screen bg-[#f4f6f9] px-5 py-10 text-slate-900 sm:grid sm:place-items-center"><div className="w-full max-w-5xl overflow-hidden rounded-[28px] border border-slate-200 bg-white shadow-[0_30px_90px_rgba(15,23,42,.12)] lg:grid lg:grid-cols-[.82fr_1.18fr]">
    <section className="relative overflow-hidden bg-[#111b2d] p-8 text-white sm:p-12"><div className="absolute -right-24 -top-24 size-64 rounded-full bg-[#e1251b]/20 blur-3xl" /><div className="relative"><div className="grid size-12 place-items-center rounded-2xl bg-[#e1251b]"><PackageCheck className="size-6" /></div><p className="mt-7 text-sm font-semibold tracking-[.18em] text-red-300">包裹智检</p><h1 className="mt-3 text-3xl font-bold leading-tight">退货包裹破损<br />AI 识别与智能定损</h1><p className="mt-5 max-w-sm text-sm leading-7 text-slate-300">演示系统支持两种身份。选择后直接进入对应页面，两个工作区互不提供跳转入口。</p><div className="mt-10 flex items-center gap-2 text-xs text-slate-400"><ShieldCheck className="size-4 text-emerald-400" />角色分区演示模式</div></div></section>
    <section className="p-7 sm:p-12"><p className="text-sm font-medium text-slate-400">欢迎使用</p><h2 className="mt-2 text-2xl font-bold">请选择身份进入</h2><p className="mt-2 text-sm text-slate-500">无需账号密码，点击身份即可查看对应功能。</p><div className="mt-8 grid gap-4">
      <a href="/user" className="group flex items-center gap-4 rounded-2xl border border-slate-200 p-5 transition hover:border-blue-200 hover:bg-blue-50/40"><span className="grid size-12 place-items-center rounded-xl bg-blue-50 text-blue-600"><UserRound className="size-5" /></span><span className="flex-1"><strong className="block text-base">我是使用者</strong><span className="mt-1 block text-sm text-slate-500">仅查看已经完成人工复核的包裹结果</span></span><ArrowRight className="size-5 text-slate-300 transition group-hover:translate-x-1 group-hover:text-blue-600" /></a>
      <a href="/staff" className="group flex items-center gap-4 rounded-2xl border border-slate-200 p-5 transition hover:border-red-200 hover:bg-red-50/40"><span className="grid size-12 place-items-center rounded-xl bg-red-50 text-[#e1251b]"><ClipboardCheck className="size-5" /></span><span className="flex-1"><strong className="block text-base">我是工作人员</strong><span className="mt-1 flex items-center gap-2 text-sm text-slate-500">人工复核操作台 <LayoutDashboard className="size-3.5" /> 数据看板</span></span><ArrowRight className="size-5 text-slate-300 transition group-hover:translate-x-1 group-hover:text-[#e1251b]" /></a>
    </div></section>
  </div></main>;
}
